[package]
name = "mamimi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
chrono = "0.4.19"
clap = "=3.0.0-beta.5"
encoding_rs_io = "0.1.7"
regex = "1.5.4"
semver = "1.0.4"
serde = "1.0.130"
url = "2.2.2"

[features]
